<a href="https://colab.research.google.com/github/sadullahmath/Exercise/blob/master/Comparing_Different_Dimensionality_Reduction_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

In [3]:
# Creating a simple data frame
df = pd.np.array([[1, 2, 3], [4, 5, 6]])
print(df.shape)
df

(2, 3)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  """Entry point for launching an IPython kernel.


array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# Defining the mean and standard deviation
mu, sigma = 0, 0.1
# Generating random sample
noise = np.random.normal(mu, sigma, [2,3])
noise.shape

(2, 3)

In [5]:
# Sampled data frame
noise

array([[ 0.10053913, -0.01912401, -0.07870251],
       [-0.04774446, -0.18017692,  0.04583832]])

In [6]:
# Creating a new data set by adding sampled data frame
df_new = df + noise
df_new

array([[1.10053913, 1.98087599, 2.92129749],
       [3.95225554, 4.81982308, 6.04583832]])